### ISSUE TITLE
Possible leaks by using RegExp.lastMatch

### ISSUE THREAD

**Issue by lingyan** [andyearnshaw/Intl.js#133]
`RegExp.lastMatch` is a static property on RegExp class.  So there is potential danger of picking up last match from another regexp replace outside of Intl.js.

I recently encountered this issue, where the lastMatch happened to have matched a huge string.  This causes `createRegExpRestore()` to [generate an invalid regular express](https://github.com/andyearnshaw/Intl.js/blob/41e1bb2aa40c713e5c393e84080af320f9b0b747/src/core.js#L2932), which then causes [`regexpState.exp.test(regexpState.input)`](https://github.com/andyearnshaw/Intl.js/blob/41e1bb2aa40c713e5c393e84080af320f9b0b747/src/core.js#L1251) to throw the following error:

```
SyntaxError: Invalid regular expression: /...some...crazily...long...string...content...omitted.../: RegExp too big
    at RegExp.test (native)
    at FormatNumber (/home/me/myapp/node_modules/intl/Intl.complete.js:1639:21)
    at NumberFormatConstructor.GetFormatNumber.F (/home/me/myapp/node_modules/intl/Intl.complete.js:1432:28)
    at PluralOffsetString.format (/home/me/myapp/node_modules/react-intl/node_modules/intl-messageformat/lib/compiler.js:192:36)
    at MessageFormat._format (/home/me/myapp/node_modules/react-intl/node_modules/intl-messageformat/lib/core.js:202:28)
    at MessageFormat._format (/home/me/myapp/node_modules/react-intl/node_modules/intl-messageformat/lib/core.js:200:28)
    at MessageFormat.format (/home/me/myapp/node_modules/react-intl/node_modules/intl-messageformat/lib/core.js:41:30)
    at [object Object].exports.default.formatMessage (/home/me/myapp/node_modules/react-intl/lib/mixin.js:101:24)
```

I will try to submit a test case for this.  Creating the issue before that, in case someone knows the fix right away.

Thanks!

**Comment by caridy** [comment]
@lingyan send me the case, and I can try to fix it :)

**Comment by lingyan** [comment]
@caridy sure.  I will send it to you as soon as I have it. thanks!

**Comment by caridy** [comment]
@lingyan can we close this one?

**Comment by lingyan** [comment]
@caridy Ah. sorry. I will close it for now, until I get time to create the test case.
