### ISSUE TITLE
Intl.js with polyfill not working on Safari

### ISSUE THREAD

**Issue by gabouy** [andyearnshaw/Intl.js#256]
We were using this library successfully but for some reason it stopped working last Friday. 

When loading the html that includes the Intl polyfill reference (https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.en) the following errors are displayed in Safari:

<img width="760" alt="polyfill-error" src="https://cloud.githubusercontent.com/assets/449957/20463304/a5d0813a-af0e-11e6-9aac-58c346091570.png">

The result is a blank page instead of the expected content loaded. 

Not sure if this is an Intl.js error, or a polyfill one, but any help would be greatly appreciated!

**Comment by caridy** [comment]
@mtlewis could this be related to #244?

**Comment by mtlewis** [comment]
@caridy Yes, I would expect this to be fixed by #244 :D

**Comment by caridy** [comment]
Ok, I will try to do the release tomorrow morning.

**Comment by ruiaraujo** [comment]
@caridy Any chance of doing a release?

**Comment by Turbo87** [comment]
@caridy friendly reminder

**Comment by chicoxyzzy** [comment]
Any progress on this?

**Comment by mtlewis** [comment]
Any news on this release @caridy?

**Comment by chicoxyzzy** [comment]
As a workaround you can use v1.2.4. But definitely project needs more collaborators!

**Comment by Turbo87** [comment]
@chicoxyzzy unfortunately that is not an option when using it with polyfill.io... 😞

**Comment by ruiaraujo** [comment]
@Turbo87 Remove it from polyfill.io and polyfill it yourself for a while until it is fixed. A bloated bundle is better than a broken site.

**Comment by Turbo87** [comment]
@ruiaraujo to be honest I'd rather work on fixing the cause of the problem, but that unfortunately seems harder than I hoped...

**Comment by caridy** [comment]
@reiniergs is helping with the tests at the moment, trying to get the test suite back to life, and validate that we are good. We don't want to push a broken build again (like the RegExp issue from last time). I'm currently out until the second week of January. Apologies for the inconvenience, and I will be very supportive of more hands on the deck, if someone has time to help.

**Comment by Turbo87** [comment]
@caridy thanks for the feedback! can you elaborate on what is wrong with the test suite? any way we can help?

**Comment by caridy** [comment]
@Turbo87 the saucelab config is a mess at the moment. On top of that, errors happening during the testing process are completely obscure (at the moment there are ~18 failures on IE, but the error tells nothing about the actual error).

**Comment by dvkndn** [comment]
Um.. just a little note that while waiting for the fix, we can also disable "RegExp cache / restore" as explained in [the documentation](https://github.com/andyearnshaw/Intl.js#regexp-cache--restore)

I'm not sure about everyone's cases, but it works for mine and I also think the document is right that is is "highly unlikely" that you can disable it.

**Comment by olaf89** [comment]
Same happening on on 1.2.5 IE10, 1.2.4 works fine

**Comment by mtlewis** [comment]
@caridy please let me know if there's anything (#244 related or otherwise) that I can do to help get the next version ready for release. :+1:

**Comment by jerone** [comment]
I just ran into this problem with the npm package for NodeJS (thus not Polyfill.io)...

```
SyntaxError: Invalid regular expression: /[\s\S]{2}(((((((())))))))[\s\S]{1})[\s\S]{3}/: Unmatched ')'
    at new RegExp (<anonymous>)
    at C:\Source\TweeDuizenden\node_modules\intl\lib\core.js:590:20
    at InitializeNumberFormat (C:\Source\TweeDuizenden\node_modules\intl\lib\core.js:2077:5)
    at new NumberFormatConstructor (C:\Source\TweeDuizenden\node_modules\intl\lib\core.js:1838:12)
    at CreateDateTimeParts (C:\Source\TweeDuizenden\node_modules\intl\lib\core.js:3898:14)
    at FormatDateTime (C:\Source\TweeDuizenden\node_modules\intl\lib\core.js:4079:17)
    at DateTimeFormatConstructor.F (C:\Source\TweeDuizenden\node_modules\intl\lib\core.js:3848:20)
    at Object.getLocaleDateString (C:\Source\TweeDuizenden\app\helpers.js:65:107)
    at C:\Source\TweeDuizenden\controllers\game.js:322:42
    at model.Query.<anonymous> (C:\Source\TweeDuizenden\node_modules\mongoose\lib\model.js:3731:16)
    at C:\Source\TweeDuizenden\node_modules\kareem\index.js:277:21
    at C:\Source\TweeDuizenden\node_modules\kareem\index.js:131:16
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

One proposed solution [above](https://github.com/andyearnshaw/Intl.js/issues/256#issuecomment-267705446) about disabling RegExp cache doesn't work.

---------

```
Intl 1.2.5
NodeJS v7.7.4
npm 4.1.2
```

**Comment by matte00** [comment]
Intl 1.2.5
NodeJS 6.10.3
Npm 5.0.4
When polyfills is applaied i get this error message:
` Invalid regular expression: /[\s\S]{4}(((((((())))))))[\s\S]{3})/: Unmatched ')'`

No news about it?

**Comment by mfollett** [comment]
Based on PR and issue discussions it looks like #244 fixed this, but there hasn't been a release since 11/16/16 when it was merged.

**Comment by dvkndn** [comment]
Wow it has been so long since this issue appear.. Now we even already dropped support for Safari < 10, which is the reason we need to use this in the first place 😂

**Comment by matte00** [comment]
Meanwhile downgrade to 1.2.4..it's works fine!

**Comment by tony99nyr** [comment]
This is still an issue.  We hard coded 1.2.4 and removed the carot from our package.json for now.

**Comment by HenokT** [comment]
Thanks to @dvkndn, [disabling regex caching](https://github.com/andyearnshaw/Intl.js#regexp-cache--restore) seems to fix the problem for me as well:

Intl.__disableRegExpRestore()

**Comment by catamphetamine** [comment]
Also having `SyntaxError: Invalid regular expression: /[\s\S]{4}(((((((())))))))[\s\S]{3})/: Unmatched ')'`.
Started having it randomly.

**Comment by sznrbrt** [comment]
Still experiencing the problem on Safari. Btw, the downgrade doesn't seem to work. 
`No matching version found for react-intl@^1.2.4`
What am I missing here?

**Comment by chicoxyzzy** [comment]
@sznrbrt this is `intl`, not `react-intl`

**Comment by mbrucher** [comment]
> `Intl` is present in all modern browsers [_except_ Internet Explorer 10, Safari 9 and iOS Safari 9.x](http://caniuse.com/#search=intl).

It's not available outside the browser, which is still something lots of people face (Node, react-*).
I had the same problem today. It's actually very annoying to get a previous version when there are requirements for >1.2.5, so would be great to get a 1.2.6 release to fix this!
